aws:
  bucket_name: smf2659-clouds
  prefix: experiments
  upload: false
create_dataset:
  column_names:
  - visible_mean
  - visible_max
  - visible_min
  - visible_mean_distribution
  - visible_contrast
  - visible_entropy
  - visible_second_angular_momentum
  - IR_mean
  - IR_max
  - IR_min
  label_column: visible_entropy
  row_range:
    end: 50
    start: 21
  separator: \s+
evaluate_performance:
  metrics:
  - auc
  - accuracy
  - confusion_matrix
  - classification_report
generate_features:
  calculate_difference:
    IR_range:
      max_col: IR_max
      min_col: IR_min
  calculate_norm_range:
    IR_norm_range:
      max_col: IR_max
      mean_col: IR_mean
      min_col: IR_min
  log_transform:
    log_entropy: visible_entropy
  multiply:
    entropy_x_contrast:
      col_a: visible_contrast
      col_b: visible_entropy
run_config:
  author: Junyi Chen
  data_source: https://archive.ics.uci.edu/ml/machine-learning-databases/undocumented/taylor/cloud.data
  dependencies: requirements.txt
  description: Classifies clouds into one of two types using features from image data.
  name: random-forest-featset-1
  output: runs
  version: v1.0
score_model:
  target_column: class
  threshold: 0.5
  use_features:
  - log_entropy
  - IR_norm_range
  - entropy_x_contrast
train_model:
  initial_features:
  - log_entropy
  - IR_norm_range
  - entropy_x_contrast
  model_type: RandomForestClassifier
  parameters:
    max_depth: 10
    n_estimators: 10
    random_state: 42
  target_column: class
  test_size: 0.2
